export const MAIN_ROUTE = '/main'
export const AUTH_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const TITLE_ROUTE = '/'
export const NOTFOUND_ROUTE = '/*'
export const PRIVACY_ROUTE = '/privacy'
export const SETTING_ROUTE = '/setting'
export const LOGOUT_ROUTE = '/logout'